#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

hook-dynamic-dockerfile-builder-dokku-image() {
  declare BUILDER_TYPE="$1" APP="$2" SOURCECODE_WORK_DIR="$3" DOKKU_IMAGE="$4"
  declare DOCKERFILE_PATH="$(fn-dynamic-dockerfile-dockerfile-path "$APP")"

  if [[ -z "$DOCKERFILE_PATH" ]]; then
    return
  fi

  fn-dynamic-dockerfile-validate-path "$BUILDER_TYPE" "$APP" "$SOURCECODE_WORK_DIR"

  declare IMAGE_NAME="$(fn-dynamic-dockerfile-image-name "$APP")"

  if [[ "$("$DOCKER_BIN" images --quiet "$IMAGE_NAME" 2>/dev/null)" != "" ]]; then
    echo "$IMAGE_NAME"
  else
    dokku_log_fail "Missing base image"
  fi
}

hook-dynamic-dockerfile-builder-dokku-image "$@"
