#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

report-cmd() {
  cmd-dynamic-dockerfile-report "$@"
}

report-cmd "$@"
