#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

set-cmd() {
  cmd-dynamic-dockerfile-set "$@"
}

set-cmd "$@"
